export const image404 = '/images/404.jpg'
export const profile = '/images/profile_LQ.jpg'
export const pixelProfile = '/images/pixel_profile_LQ.jpg'
export const favicon = '/images/favicon.png'
export const cvPdf = '/files/Mario Payan CV.pdf'
